#pragma once

#include "..\..\..\module\baseclass\ExBaseObject.h"
#include "..\..\..\module\baseclass\ExBaseList.h"
#include "RptXmlRWKeys.h"

//////////////////////////////////////////////////////////////////////////
//报告模板类ID定义
#define GBRCLASSID_BASECLASS       (CLASSID_BASECLASS + 0X00040000)
#define GBRCLASSID_EXLISTCLASS     (CLASSID_EXLISTCLASS + 0X00040000)

#define RPTCLASSID_RPTBKMK			(GBRCLASSID_BASECLASS   + 0x00000001)
#define RPTCLASSID_RPTAREA			(GBRCLASSID_EXLISTCLASS + 0x00000002)
#define RPTCLASSID_RPTDATA			(GBRCLASSID_EXLISTCLASS + 0x00000003)
#define RPTCLASSID_RPTDATAS			(GBRCLASSID_EXLISTCLASS + 0x00000004)
#define RPTCLASSID_RPTITEM			(GBRCLASSID_EXLISTCLASS + 0x00000005)
#define RPTCLASSID_RPTITEMS			(GBRCLASSID_EXLISTCLASS + 0x00000006)
#define RPTCLASSID_RPTREPORTMAP		(GBRCLASSID_EXLISTCLASS + 0x00000007)
#define RPTCLASSID_RPTEDITINTERFACE	(GBRCLASSID_EXLISTCLASS + 0x00000008)
#define RPTCLASSID_RPTWORDRPTEDIT	(GBRCLASSID_EXLISTCLASS + 0x00000009)
#define RPTCLASSID_RPTWPSRPTEDIT	(GBRCLASSID_EXLISTCLASS + 0x0000000A)
#define RPTCLASSID_RPTSYSTEMRPTEDIT	(GBRCLASSID_EXLISTCLASS + 0x0000000B)
