
SOURCES +=  \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dictbuilder.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dictlist.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dicttrie.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/lpicache.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/matrixsearch.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/mystdlib.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/ngram.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/pinyinime.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/searchutility.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/spellingtable.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/spellingtrie.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/splparser.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/sync.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/userdict.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/utf16char.cpp \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/utf16reader.cpp \
$$PWD/Main/Ctrls/HKButton.cpp \
$$PWD/Main/Ctrls/HKButtonGroup.cpp \
$$PWD/Main/Ctrls/HKWgtFileMngrGrid.cpp \
$$PWD/Main/Ctrls/HKWgtLinux.cpp \
$$PWD/Main/Ctrls/HKWgtStyle.cpp \
$$PWD/Main/Ctrls/HkTabWidget.cpp \
$$PWD/Main/Ctrls/HKWgtText.cpp \
$$PWD/Main/Module/HKWgtBase.cpp \
$$PWD/Main/Module/HKWgtBaseList.cpp \
$$PWD/Main/Module/HKWgtCmdExecTool.cpp \
$$PWD/Main/Module/HKWgtCmdThread.cpp \
$$PWD/Main/Module/HKWgtFactory.cpp \
$$PWD/Main/SttXuiData/SttXMainConfigGlobal.cpp \
$$PWD/Main/SttXuiData/SttXuiDataBase.cpp \
$$PWD/Main/SttXuiData/SttXuiDataBtnsGroup.cpp \
$$PWD/Main/SttXuiData/SttXuiDataButton.cpp \
$$PWD/Main/SttXuiData/SttXuiDataCmd.cpp \
$$PWD/Main/SttXuiData/SttXuiDataFileMngrGrid.cpp \
$$PWD/Main/SttXuiData/SttXuiDataFileType.cpp \
$$PWD/Main/SttXuiData/SttXuiDataFileTypes.cpp \
$$PWD/Main/SttXuiData/SttXuiDataFont.cpp \
$$PWD/Main/SttXuiData/SttXuiDataGlobal.cpp \
$$PWD/Main/SttXuiData/SttXuiDataMainConfig.cpp \
$$PWD/Main/SttXuiData/SttXuiDataTab.cpp \
$$PWD/Main/SttXuiData/SttXuiDataTabs.cpp \
$$PWD/Main/SttXuiData/SttXuiDataTestBtnsGroup.cpp \
$$PWD/Main/SttXuiData/SttXuiDataText.cpp \
$$PWD/UI/SCL/QSttSelSclFileWidget.cpp \
$$PWD/UI/SCL/QSttSelSclIedWidget.cpp \
$$PWD/UI/SCL/SttSelSclFileGrid.cpp \
$$PWD/UI/SCL/SttSelSclIedGrid.cpp \
$$PWD/LiveUpdate/SttLiveUpdateShell.cpp \
$$PWD/LiveUpdate/SttUpdateCfg.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListGridBase.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QGridDefine.cpp \
$$PWD/UI/Module/PopupDialog/SttFileDlgBase.cpp \
$$PWD/UI/Module/PopupDialog/SttFileMngrTool.cpp \
$$PWD/UI/Module/PopupDialog/SttFileMngrTree.cpp \
$$PWD/UI/Module/PopupDialog/SttPopupOpenDialog.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollComboBox.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollCtrlInterface.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollListView.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollTreeWidget.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollTableWidget.cpp \
$$PWD/UI/Controls/SttCheckBox.cpp \
$$PWD/Main/HKMainFrameBase.cpp \
$$PWD/SttTestBase/SttComplexCalApi.cpp \
$$PWD/SttTestBase/SttComplexp.cpp \
$$PWD/SttTestBase/SttMacroXmlKeys.cpp \
$$PWD/SttTestBase/SttXmlSerialize.cpp \
$$PWD/SttTestBase/SttXmlSerializeBase.cpp \
$$PWD/SttSocket/SttCmdOverTimeMngr.cpp \
$$PWD/SttSocket/SttServerSocketDataBase.cpp \
$$PWD/SttSocket/SttSocketDataBase.cpp \
$$PWD/SttSocket/SttSocketDataBase_File.cpp \
$$PWD/SttCmd/SttAdjustCmd.cpp \
$$PWD/SttCmd/SttAssistCmd.cpp \
$$PWD/SttCmd/SttAtsCmd.cpp \
$$PWD/SttCmd/SttChMap.cpp \
$$PWD/SttCmd/SttChMaps.cpp \
$$PWD/SttCmd/SttCmdBase.cpp \
$$PWD/SttCmd/SttCmdCreator.cpp \
$$PWD/SttCmd/SttCmdData.cpp \
$$PWD/SttCmd/SttCmdDefineGlobal.cpp \
$$PWD/SttCmd/SttDebugCmd.cpp \
$$PWD/SttCmd/SttHdCh.cpp \
$$PWD/SttCmd/SttHdChs.cpp \
$$PWD/SttCmd/SttIotCmd.cpp \
$$PWD/SttCmd/SttIotDevice.cpp \
$$PWD/SttCmd/SttIotDevices.cpp \
$$PWD/SttCmd/SttIotNode.cpp \
$$PWD/SttCmd/SttIotTopo.cpp \
$$PWD/SttCmd/SttMacro.cpp \
$$PWD/SttCmd/SttMsg.cpp \
$$PWD/SttCmd/SttMsgs.cpp \
$$PWD/SttCmd/SttParas.cpp \
$$PWD/SttCmd/SttRemoteCmd.cpp \
$$PWD/SttCmd/SttRptMapDatas.cpp \
$$PWD/SttCmd/SttSysState.cpp \
$$PWD/SttCmd/SttSystemCmd.cpp \
$$PWD/SttCmd/SttTestCmd.cpp \
$$PWD/TestClient/SttTestClientBase.cpp \
$$PWD/Engine/SttClientTestEngine.cpp \
$$PWD/Engine/SttRemoteClientTestEngine.cpp \
$$PWD/Engine/SttServerNativeConfig.cpp \
$$PWD/Engine/SttServerTestCtrlCntr.cpp \
$$PWD/Engine/SttTestEngineBase.cpp \
$$PWD/Engine/SttTestEngineClientData.cpp \
$$PWD/Engine/SttTestEngineRemoteClientData.cpp \
$$PWD/Engine/SttTestEngineServerBase.cpp \
$$PWD/Engine/SttTestEngineServerData.cpp \
$$PWD/SttTestAppConfig/SttTestAppCfg.cpp \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.cpp \
$$PWD/SttProtocolBufBase.cpp \
$$PWD/SttAuthority/SttTestClientUser.cpp \
$$PWD/SttAuthority/SttTestClientUserMngr.cpp \
$$PWD/SttAuthority/SttTestRemoteRegister.cpp \
$$PWD/SttFileToolMngr.cpp \
$$PWD/SttCmd/GuideBook/SttCommCmd.cpp \
$$PWD/SttCmd/GuideBook/SttContents.cpp \
$$PWD/SttCmd/GuideBook/SttDataObj.cpp \
$$PWD/SttCmd/GuideBook/SttDevice.cpp \
$$PWD/SttCmd/GuideBook/SttGuideBook.cpp \
$$PWD/SttCmd/GuideBook/SttItemBase.cpp \
$$PWD/SttCmd/GuideBook/SttItemRsltExpr.cpp \
$$PWD/SttCmd/GuideBook/SttItems.cpp \
$$PWD/SttCmd/GuideBook/SttItemStateObject.cpp \
$$PWD/SttCmd/GuideBook/SttJobGuide.cpp \
$$PWD/SttCmd/GuideBook/SttMacroCharItems.cpp \
$$PWD/SttCmd/GuideBook/SttMacroTest.cpp \
$$PWD/SttCmd/GuideBook/SttReport.cpp \
$$PWD/SttCmd/GuideBook/SttReportMap.cpp \
$$PWD/SttCmd/GuideBook/SttReports.cpp \
$$PWD/SttCmd/GuideBook/SttRptData.cpp \
$$PWD/SttCmd/GuideBook/SttSafety.cpp \
$$PWD/SttCmd/GuideBook/SttSysParaEdit.cpp \
$$PWD/SttCmd/GuideBook/SttSysParas.cpp \
$$PWD/SttCmd/GuideBook/SttTestMacroCharParas.cpp \
$$PWD/SttCmd/GuideBook/SttTestMacroUiParas.cpp \
$$PWD/SttSocket/TestTerminal/SttClientSocketBase.cpp \
$$PWD/SttSocket/TestTerminal/QT/SttClientSocket.cpp \
$$PWD/SttRegisterCode.cpp \
$$PWD/SttSocket/TestServer/SttTestServerSocketBase.cpp \
$$PWD/SttSocket/TestServer/QT/SttServerClientSocket.cpp \
$$PWD/API/NetworkInterface.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.cpp \
$$PWD/SttTest/SttTestGlobaoConfig.cpp \
$$PWD/SttSocket/TestServer/SttServerClientSocketBase.cpp \
$$PWD/XLangResource_Native.cpp \
$$PWD/Main/HKMainApplicationBase.cpp

HEADERS += \
../../Module/OSInterface/QT/stdafx.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/atomdictbase.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dictbuilder.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dictdef.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dictlist.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/dicttrie.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/lpicache.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/matrixsearch.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/mystdlib.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/ngram.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/pinyinime.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/searchutility.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/spellingtable.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/spellingtrie.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/splparser.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/sync.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/userdict.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/utf16char.h \
$$PWD/UI/SoftKeyboard/Keyboard/googlepinyin/utf16reader.h \
$$PWD/Main/Ctrls/HKButton.h \
$$PWD/Main/Ctrls/HKButtonGroup.h \
$$PWD/Main/Ctrls/HKWgtFileMngrGrid.h \
$$PWD/Main/Ctrls/HKWgtLinux.h \
$$PWD/Main/Ctrls/HKWgtStyle.h \
$$PWD/Main/Ctrls/HkTabWidget.h \
$$PWD/Main/Ctrls/HKWgtText.h \
$$PWD/Main/Module/HKWgtBase.h \
$$PWD/Main/Module/HKWgtBaseList.h \
$$PWD/Main/Module/HKWgtCmdExecTool.h \
$$PWD/Main/Module/HKWgtCmdThread.h \
$$PWD/Main/Module/HKWgtFactory.h \
$$PWD/Main/SttXuiData/SttXMainConfigGlobal.h \
$$PWD/Main/SttXuiData/SttXuiDataBase.h \
$$PWD/Main/SttXuiData/SttXuiDataBtnsGroup.h \
$$PWD/Main/SttXuiData/SttXuiDataButton.h \
$$PWD/Main/SttXuiData/SttXuiDataCmd.h \
$$PWD/Main/SttXuiData/SttXuiDataFileMngrGrid.h \
$$PWD/Main/SttXuiData/SttXuiDataFileType.h \
$$PWD/Main/SttXuiData/SttXuiDataFileTypes.h \
$$PWD/Main/SttXuiData/SttXuiDataFont.h \
$$PWD/Main/SttXuiData/SttXuiDataGlobal.h \
$$PWD/Main/SttXuiData/SttXuiDataMainConfig.h \
$$PWD/Main/SttXuiData/SttXuiDataTab.h \
$$PWD/Main/SttXuiData/SttXuiDataTabs.h \
$$PWD/Main/SttXuiData/SttXuiDataTestBtnsGroup.h \
$$PWD/Main/SttXuiData/SttXuiDataText.h \
$$PWD/UI/SCL/QSttSelSclFileWidget.h \
$$PWD/UI/SCL/QSttSelSclIedWidget.h \
$$PWD/UI/SCL/SttSelSclFileGrid.h \
$$PWD/UI/SCL/SttSelSclIedGrid.h \
$$PWD/LiveUpdate/SttLiveUpdateDef.h \
$$PWD/LiveUpdate/SttLiveUpdateShell.h \
$$PWD/LiveUpdate/SttUpdateCfg.h \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.h \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListGridBase.h \
$$PWD/UI/Module/QExBaseListGridBase/QGridDefine.h \
$$PWD/UI/Module/PopupDialog/SttFileDlgBase.h \
$$PWD/UI/Module/PopupDialog/SttFileMngrTool.h \
$$PWD/UI/Module/PopupDialog/SttFileMngrTree.h \
$$PWD/UI/Module/PopupDialog/SttPopupOpenDialog.h \
$$PWD/UI/Module/ScrollCtrl/ScrollComboBox.h \
$$PWD/UI/Module/ScrollCtrl/ScrollCtrlInterface.h \
$$PWD/UI/Module/ScrollCtrl/ScrollListView.h \
$$PWD/UI/Module/ScrollCtrl/ScrollTreeWidget.h \
$$PWD/UI/Module/ScrollCtrl/ScrollTableWidget.h \
$$PWD/UI/Controls/SttCheckBox.h \
$$PWD/XLangResource_Native.h \
$$PWD/Main/SttMainArgvDef.h \
$$PWD/Main/HKMainApplicationBase.h \
$$PWD/Main/HKMainFrameBase.h \
$$PWD/SttTestBase/SttComplexCalApi.h \
$$PWD/SttTestBase/SttComplexp.h \
$$PWD/SttTestBase/SttMacroXmlKeys.h \
$$PWD/SttTestBase/SttXmlSerialize.h \
$$PWD/SttTestBase/SttXmlSerializeBase.h \
$$PWD/SttSocket/SttCmdOverTimeMngr.h \
$$PWD/SttSocket/SttServerSocketDataBase.h \
$$PWD/SttSocket/SttSocketDataBase.h \
$$PWD/SttSocket/SttSocketDataBase_File.h \
$$PWD/SttCmd/SttAdjustCmd.h \
$$PWD/SttCmd/SttAssistCmd.h \
$$PWD/SttCmd/SttAtsCmd.h \
$$PWD/SttCmd/SttChMap.h \
$$PWD/SttCmd/SttChMaps.h \
$$PWD/SttCmd/SttCmdBase.h \
$$PWD/SttCmd/SttCmdCreator.h \
$$PWD/SttCmd/SttCmdData.h \
$$PWD/SttCmd/SttCmdDefineGlobal.h \
$$PWD/SttCmd/SttDebugCmd.h \
$$PWD/SttCmd/SttHdCh.h \
$$PWD/SttCmd/SttHdChs.h \
$$PWD/SttCmd/SttIotCmd.h \
$$PWD/SttCmd/SttIotDevice.h \
$$PWD/SttCmd/SttIotDevices.h \
$$PWD/SttCmd/SttIotNode.h \
$$PWD/SttCmd/SttIotTopo.h \
$$PWD/SttCmd/SttMacro.h \
$$PWD/SttCmd/SttMsg.h \
$$PWD/SttCmd/SttMsgs.h \
$$PWD/SttCmd/SttParas.h \
$$PWD/SttCmd/SttRemoteCmd.h \
$$PWD/SttCmd/SttRptMapDatas.h \
$$PWD/SttCmd/SttSysState.h \
$$PWD/SttCmd/SttSystemCmd.h \
$$PWD/SttCmd/SttTestCmd.h \
$$PWD/TestClient/SttMacroTestInterface.h \
$$PWD/TestClient/SttTestClientBase.h \
$$PWD/Engine/SttClientTestEngine.h \
$$PWD/Engine/SttRemoteClientTestEngine.h \
$$PWD/Engine/SttServerNativeConfig.h \
$$PWD/Engine/SttServerTestCtrlCntr.h \
$$PWD/Engine/SttTestEngineBase.h \
$$PWD/Engine/SttTestEngineClientData.h \
$$PWD/Engine/SttTestEngineRemoteClientData.h \
$$PWD/Engine/SttTestEngineServerBase.h \
$$PWD/Engine/SttTestEngineServerData.h \
$$PWD/SttTestAppConfig/SttTestAppCfg.h \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.h \
$$PWD/SttProtocolBufBase.h \
$$PWD/SttAuthority/SttTestClientUser.h \
$$PWD/SttAuthority/SttTestClientUserMngr.h \
$$PWD/SttAuthority/SttTestRemoteRegister.h \
$$PWD/SttFileToolMngr.h \
$$PWD/SttCmd/GuideBook/SttCommCmd.h \
$$PWD/SttCmd/GuideBook/SttContents.h \
$$PWD/SttCmd/GuideBook/SttDataObj.h \
$$PWD/SttCmd/GuideBook/SttDevice.h \
$$PWD/SttCmd/GuideBook/SttGuideBook.h \
$$PWD/SttCmd/GuideBook/SttItemBase.h \
$$PWD/SttCmd/GuideBook/SttItemRsltExpr.h \
$$PWD/SttCmd/GuideBook/SttItems.h \
$$PWD/SttCmd/GuideBook/SttItemStateObject.h \
$$PWD/SttCmd/GuideBook/SttJobGuide.h \
$$PWD/SttCmd/GuideBook/SttMacroCharItems.h \
$$PWD/SttCmd/GuideBook/SttMacroTest.h \
$$PWD/SttCmd/GuideBook/SttReport.h \
$$PWD/SttCmd/GuideBook/SttReportMap.h \
$$PWD/SttCmd/GuideBook/SttReports.h \
$$PWD/SttCmd/GuideBook/SttRptData.h \
$$PWD/SttCmd/GuideBook/SttSafety.h \
$$PWD/SttCmd/GuideBook/SttSysParaEdit.h \
$$PWD/SttCmd/GuideBook/SttSysParas.h \
$$PWD/SttCmd/GuideBook/SttTestMacroCharParas.h \
$$PWD/SttCmd/GuideBook/SttTestMacroUiParas.h \
$$PWD/SttSocket/TestTerminal/SttClientSocketBase.h \
$$PWD/SttSocket/TestTerminal/QT/SttClientSocket.h \
$$PWD/SttRegisterCode.h \
$$PWD/SttSocket/TestServer/SttTestServerSocketBase.h \
$$PWD/SttSocket/TestServer/QT/SttServerClientSocket.h \
$$PWD/API/NetworkInterface.h \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.h \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.h \
$$PWD/SttTest/Common/tmt_common_def.h \
$$PWD/SttTest/SttTestGlobaoConfig.h \
$$PWD/SttSocket/TestServer/SttServerClientSocketBase.h \

FORMS    += \
